name: Nx Angular Benchmarks
on: [push]
jobs:
  Run-Benchmarks:
    runs-on: ubuntu-latest
    steps:
      - name: Install Hyperfine
        run: wget https://github.com/sharkdp/hyperfine/releases/download/v1.12.0/hyperfine_1.12.0_amd64.deb; sudo dpkg -i hyperfine_1.12.0_amd64.deb
      - name: Checkout Repository Code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install Packages
        run: yarn install
      - name: Benchmark Build - Cold
        run: yarn benchmark:build:cold
      - name: Benchmark Build - Cache
        run: yarn benchmark:build:cache
      - name: Benchmark Lint - Cold
        run: yarn benchmark:lint:cold
      - name: Benchmark Test - Cold
        run: yarn benchmark:test:cold
      - name: Upload Benchmark Results
        run: |
          FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }} \
          FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }} \
          FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }} \
          FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }} \
          FIREBASE_MESSAGE_SENDER_ID=${{ secrets.FIREBASE_MESSAGE_SENDER_ID }} \
          FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }} \
          node --experimental-json-modules tools/scripts/upload-benchmark-results.mjs
